const HEROES = {
  Western: {
    Bandido: {
      heroClass: 'Bandido',
      stats: {
        Agility: 3,
        Cunning: 4,
        Spirit: 2,
        Strength: 3,
        Lore: 1,
        Luck: 3,
        Initiative: 5
      },
      combat: 2,
      maxGrit: 2,
      toHit: { melee: '4+', ranged: '4+' },
      health: 10,
      sanity: 12,
      defense: '4+',
      willpower: '4+',
      abilities: ['Quick Draw', 'Holdout Pistol'],
      skillTreeId: 'Bandido',
    },
    Cowboy: {
      heroClass: 'Cowboy',
      stats: {
        Agility: 3,
        Cunning: 2,
        Spirit: 2,
        Strength: 3,
        Lore: 1,
        Luck: 3,
        Initiative: 4
      },
      combat: 2,
      maxGrit: 2,
      toHit: { melee: '4+', ranged: '3+' },
      health: 12,
      sanity: 10,
      defense: '4+',
      willpower: '5+',
      abilities: ['Deadeye Shot', 'Frontier Reflexes'],
      skillTreeId: 'Cowboy',
    },
    DarkStoneShaman: {
      heroClass: 'DarkStoneShaman',
      stats: {
        Agility: 2,
        Cunning: 3,
        Spirit: 4,
        Strength: 2,
        Lore: 3,
        Luck: 2,
        Initiative: 3
      },
      combat: 1,
      maxGrit: 2,
      toHit: { melee: '5+', ranged: '4+' },
      health: 10,
      sanity: 14,
      defense: '5+',
      willpower: '3+',
      abilities: ['Dark Stone Ritual', 'Spirit Channeling'],
      skillTreeId: 'DarkStoneShaman',
    },
    Drifter: {
      heroClass: 'Drifter',
      stats: {
        Agility: 3,
        Cunning: 3,
        Spirit: 3,
        Strength: 2,
        Lore: 2,
        Luck: 3,
        Initiative: 4
      },
      combat: 2,
      maxGrit: 2,
      toHit: { melee: '4+', ranged: '4+' },
      health: 11,
      sanity: 11,
      defense: '4+',
      willpower: '4+',
      abilities: ['Wanderer', 'Last Stand'],
      skillTreeId: 'Drifter',
    },
    JargonoNative: {
      heroClass: 'JargonoNative',
      stats: {
        Agility: 4,
        Cunning: 2,
        Spirit: 3,
        Strength: 3,
        Lore: 1,
        Luck: 2,
        Initiative: 5
      },
      combat: 2,
      maxGrit: 2,
      toHit: { melee: '3+', ranged: '5+' },
      health: 12,
      sanity: 10,
      defense: '4+',
      willpower: '4+',
      abilities: ['Jungle Instincts', 'Tribal Weaponry'],
      skillTreeId: 'JargonoNative',
    },
    TrederranVeteran: {
      heroClass: 'TrederranVeteran',
      stats: {
        Agility: 2,
        Cunning: 3,
        Spirit: 2,
        Strength: 3,
        Lore: 1,
        Luck: 4,
        Initiative: 4
      },
      combat: 2,
      maxGrit: 2,
      toHit: { melee: '4+', ranged: '3+' },
      health: 11,
      sanity: 11,
      defense: '4+',
      willpower: '4+',
      abilities: ['Trederran Faction', 'Tactical Experience'],
      skillTreeId: 'TrederranVeteran',
    },
  }
};

export { HEROES };
